version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  groups:
    rjsf:
      patterns:
      - "@rjsf*"
    vite:
      patterns:
      - "vite*"
      - "@vite*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
