name: Deploy to GitHub Pages
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Deploy-to-GitHub-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci
      
      - name: Set package version
        run: |
            LATEST_TAG=$(git describe --tags --abbrev=0 | sed s/^v//\;s/$// | tr -d '"')
            CURRENT_BRANCH=$(git branch --show-current | tr -d '"')
            CURRENT_COMMIT=$(git rev-parse --short HEAD)
            VERSION_NUMBER=".version=\"${LATEST_TAG}-${CURRENT_BRANCH}-${CURRENT_COMMIT}\""
            jq ${VERSION_NUMBER} package.json > temp_package.json
            mv temp_package.json package.json
      
      - name: Copy user name and email from most recent commit
        run: |
            git config user.name "$(git log -n 1 --pretty=format:%an)"
            git config user.email "$(git log -n 1 --pretty=format:%ae)"
            echo $(git config user.name)
            echo $(git config user.email)

      - name: Publish to gh pages
        run: npm run publish-to-gh-pages
